name: HACS Validation

on:
  push:
  pull_request:

jobs:
  hacs-validation:
    runs-on: ubuntu-latest
    steps:
      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: plugin
